language: node_js
node_js:
 - "node"
services:
 - mongodb
 - node server.js
install:
 - sudo snap install pdftk
 - npm install
 - npm install -g istanbul
 - npm install -g codecov
script:
script:
 -  istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov

