language: node_js
node_js:
 - "node"
services:
 - mongodb
install:
 - sudo snap install pdftk
 - npm install
script:
 - node server.js &
 - npm test
 - npm run coverage
after_success:
 - npm run coverage
