language: node_js
node_js:
 - "node"
services:
 - mongodb
install:
 - sudo snap install pdftk
 - npm install
 - npm install -g istanbul
 - npm install -g codecov
script:
 - node server.js & istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
 - lsof -i tcp:8080 & kill -9 PID
