language: node_js
node_js:
 - "node"
install:
 - sudo add-apt-repository ppa:malteworld/ppa
 - sudo apt update
 - sudo apt install pdftk
 - npm install
 - npm install -g istanbul
 - npm install -g codecov
script:
 - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
