language: node_js
node_js:
 - "node"
services:
 - mongodb
install:
 - sudo snap install pdftk
 - source installdb.sh &
 - npm install
 - npm rebuild
script:
 - node server.js &
 - npm test
 - npm run coverage
